def fitness(q):
    """ Essentially, the only thing that you need to define
    is the fitness function. The population is
    generated by a function in search.py. As the
    AG in AIMA is designed to maximize,
    we need to invert the condition,
    to count how many non atacks we have. """	  
    non_attacking = 0
    for row1 in range(len(q)):
        for row2 in range(row1+1, len(q)):
            col1 = int(q[row1])
            col2 = int(q[row2])
            row_diff = row1 - row2
            col_diff = col1 - col2

            if col1 != col2 and row_diff != col_diff and row_diff != -col_diff:
                non_attacking += 1

    return non_attacking